### ISSUE TITLE
Files from CTAN Download and Overleaf Download not the same

### ISSUE THREAD

**Issue by AnnabellBrocker** [gi-ev/LNI#159]
The download of the Latex template from CTAN does not contain the same files as the Overleaf template:

**CTAN files:**
- CHANGELOG.md
- CONTRIBUTING.md
- lni.dtx
- lni.ins
- lni.pdf
- lni-author-template.tex
- lni-instructions.pdf
- lni-paper-example-de.bib
- lni-paper-example-de.tex
- README.md

**Overleaf files:**
- CHANGELOG.md
- CONTRIBUTING.md
- lni.bst
- lni.cls
- lni.pdf
- lnig.bst
- lni-paper-example-de.bib
- lni-paper-example-de.tex
- README.md

The CTAN template does not work correctly as it is missing the lni.cls file.

**Comment by sieversMartin** [comment]
That is intentional. The dtx file is a special format to combine programming with documentation. Using an .ins file the needed files (.bst, .cls,. bib) are derived from that file.

However, these differences are not known to most "normal" users. Therefore we already discussed making it clearer.

**Comment by sieversMartin** [comment]
One more comment. CTAN files are not meant for downloading them yourself, but they are the basis for the TeX distributions TeX Live and MiKTeX. Usually it is _not_ necessary to download files from CTAN as the package becomes part of the distribution within a few days.

If you download the files, you have to call `latex lni.ins` or `pdflatex ins.dtx` in order to get all necessary files.
