### ISSUE TITLE
Option `oldfonts` incompatible with package `amsmath`

### ISSUE THREAD

**Issue by jmkeil** [gi-ev/LNI#71]
Using the following parameter and preamble
```
\documentclass[oldfonts]{lni}
\usepackage{amsmath,mathtools}
```
results in the following error:
```
! Package cleveref Error: cleveref must be loaded after amsmath!.
```

**Comment by sieversMartin** [comment]
Thank you for your report. This is not are real incompatibility, but `cleverref` as well as `hyperef` and `hypcap` have to be loaded last, even if the user loads additionall packages.

**Comment by koppor** [comment]
I hope, this won't break for packages which have to be loaded after hyperref. Could pkgloader (https://github.com/mhelvens/latex-pkgloader) be an option? Even though the author wants to have everything documented instead of just relying on experiences.https://github.com/mhelvens/latex-pkgloader/pull/16

**Comment by sieversMartin** [comment]
What exactly do you mean? I changed the loading order already. Which packages do you have in mind? `glossaries`?
