### ISSUE TITLE
problems, when using lni-ger + biblatex + authorarchive

### ISSUE THREAD

**Issue by lhumb** [gi-ev/LNI#79]
Already documented at
https://github.com/adbrucker/authorarchive/issues/18
it seems to not accepting the embedding of *.bib for the preprint.
[lni-author-template.pdf](https://github.com/gi-ev/LNI/files/3610790/lni-author-template.pdf)
and there are some misaligned elements at the bottom … 

TNX Ludger

**Comment by sieversMartin** [comment]
Am 13.09.19 um 18:02 schrieb lhumb:
> Already documented at
> adbrucker/authorarchive#18
> <https://github.com/adbrucker/authorarchive/issues/18>
> it seems to not accepting the embedding of *.bib for the preprint.
> lni-author-template.pdf
> <https://github.com/gi-ev/LNI/files/3610790/lni-author-template.pdf>
> and there are some misaligned elements at the bottom …

The problem is caused by the postponed loading of hyperref in the lni class:
\AtEndPreamble{%
      \RequirePackage[pdfusetitle,bookmarks=false]{hyperref}
...

A quick fix is to postpone the loading of authorarchive as well:
\documentclass{lni}
\AtEndPreamble{\usepackage{authorarchive}}

Best regards,
Martin

-- 

Martin Sievers -- Einfach schöner publizieren

Im Alten Garten 5
54296 Trier

Telefon:  +49 (0) 651 4936567-0
Telefax:  +49 (0) 651 4936567-9
Mobil:    +49 (0) 179 7347726

Internet: http://www.schoenerpublizieren.de
E-Mail:   info@schoenerpublizieren.de

**Comment by lhumb** [comment]
TNX for this hint!
The problem with not embedding local bib for the preprint-version with package authorarchive remains…open
